### ISSUE TITLE
Gif not change on page reload

### ISSUE THREAD

**Issue by khawajaazfar** [samadpls/Programing-Gifs#10]
Hey there, Great repo but there is problem i have seen gif folder it contain more than 20 gif and it should be on page reloading but the gifs are not changing on page reload it's only displaying one gif .

**Comment by samadpls** [comment]
hey @khawajaazfar2000  I have tried to resolve the issue but it still persists.

**Comment by samadpls** [comment]
The issue may persist because of incorrect handling of cache headers in the response. The browser may be caching the content of the first request and not making subsequent requests for updated content.

**Comment by khawajaazfar** [comment]
🤧😢

**Comment by samadpls** [comment]
> 🤧😢

Hey @khawajaazfar2000  copy past the url again from readme its working now…❣✌️

**Comment by khawajaazfar** [comment]
Wow, Great 🤩🙂
