### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by khawajaazfar** [samadpls/Programing-Gifs#9]
Hey man, great project but now it's not working i have merge it on my github profile but it's not working

**Comment by samadpls** [comment]
yeah, I am sorry for this inconvenience. due to a change in the policy of the Heroku app, the domain is not free anymore, I am trying to shift this code in node js so I can deploy it in the Cyclic app

**Comment by samadpls** [comment]
I will inshallah fix it by tomorrow.

**Comment by samadpls** [comment]
@khawajaazfar2000  The app is not live and can be used. The URL has been changed, so please update it. Thank you for letting me know about this issue

**Comment by khawajaazfar** [comment]
Great its working but now it's only displaying one gif its not changing. 
BTW what was problem and how you solve it?
